[package]
name = "wolf_project_210"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.41", features = ["serde"] }
csv = "1.3.1"
ndarray = "0.16.1"
petgraph = "0.8.1"
plotters = "0.3.7"
serde = { version = "1.0.219", features = ["derive"] }
